---    
  - name: Copy ISO to KVM node from infra_vm
    ansible.builtin.shell: |
      scp -o StrictHostKeyChecking=no {{ install_dir }}/rhcos-{{ item }}.iso root@{{ inventory_hostname }}:/var/morpheus/kvm/images/
    delegate_to: "{{ groups['infra_vm'][0] }}"
    loop:
      - bootstrap
      - master
      - worker
