- name: Update apt cache (best practice)
  apt:
    update_cache: yes
  become: true
  changed_when: false

- name: Prepare hosts (Ubuntu)
  apt:
    name:
      - bind9
      - bind9utils
      - bind9-doc
      - firewalld
    state: present

- name: Enable named service
  command: systemctl enable named

- name: Start named service
  command: systemctl start named

- name: Status named service
  command: systemctl status named
  register: output

- debug:
    var: output.stdout_lines

