---
- name: Create bootstrap VM on KVM node1
  shell:
    cmd: >-
        virt-install
        -n rhocpbootstrap
        --description "Bootstrap Machine for Openshift 4 Cluster"
        --memory {{ vm_mem }}
        --vcpus={{ vm_cpu }}
        --os-variant=rhel9.0
        --os-type linux
        --cdrom /var/morpheus/kvm/images/rhcos-bootstrap.iso
        --disk pool=mvm-volumes,device=disk,size={{ vm_size }},bus=virtio
        --network network=Management,model=virtio,virtualport_type=openvswitch,mac={% for item in ocp_bootstrap %}{{ item.mac_address }}{% endfor %}
        --autostart 
        --console pty,target_type=virtio
        --graphics=none 
        --noautoconsole 
        --wait 15
  delegate_to: "{{ groups['kvm_nodes'][0] }}" 


- name: Create master1 VM on KVM node1
  shell:
    cmd: >-
        virt-install
        -n rhocpmaster11
        --description "Master1 Machine for Openshift 4 Cluster"
        --memory {{ vm_mem }}
        --vcpus={{ vm_cpu }}  
        --os-variant=rhel9.0
        --os-type linux
        --cdrom /var/morpheus/kvm/images/rhcos-master.iso
        --disk pool=mvm-volumes,device=disk,size={{ vm_size }},bus=virtio
        --network network=Management,model=virtio,virtualport_type=openvswitch,mac={{ocp_masters[0].mac_address}}
        --autostart 
        --console pty,target_type=virtio
        --graphics=none 
        --noautoconsole 
        --wait 15
  delegate_to: "{{ groups['kvm_nodes'][0] }}" 


- name: Create Master2 VM on KVM node2
  shell:
    cmd: >-
        virt-install
        -n rhocpmaster12
        --description "Master2 Machine for Openshift 4 Cluster"
        --memory {{ vm_mem }}
        --vcpus={{ vm_cpu }}
        --os-variant=rhel9.0
        --os-type linux
        --cdrom /var/morpheus/kvm/images/rhcos-master.iso
        --disk pool=mvm-volumes,device=disk,size={{ vm_size }},bus=virtio
        --network network=Management,model=virtio,virtualport_type=openvswitch,mac={{ocp_masters[1].mac_address}}
        --autostart 
        --console pty,target_type=virtio
        --graphics=none 
        --noautoconsole 
        --wait 15
    become: true
  delegate_to: "{{ groups['kvm_nodes'][1] }}"


- name: Create Master3 VM on KVM node
  shell:
    cmd: >-
        virt-install
        -n  rhocpmaster13
        --description "Master3 Machine for Openshift 4 Cluster"
        --memory {{ vm_mem }}
        --vcpus={{ vm_cpu }}
        --os-variant=rhel9.0
        --os-type linux
        ---cdrom /var/morpheus/kvm/images/rhcos-master.iso
        --disk pool=mvm-volumes,device=disk,size={{ vm_size }},bus=virtio
        --network network=Management,model=virtio,virtualport_type=openvswitch,mac={{ocp_masters[2].mac_address}}
        --autostart 
        --console pty,target_type=virtio
        --graphics=none 
        --noautoconsole 
        --wait 15
    become: true
  delegate_to: "{{ groups['kvm_nodes'][2] }}"




