---
  - name: Delete existing dist folder
    file:
      path: "{{ dest_base_path }}/playbooks/roles/generate_ignition_files/ignitions"
      state: absent

  - name: Create Ignition directory
    file:
      path: "{{ dest_base_path }}/playbooks/roles/generate_ignition_files/ignitions"
      state: directory

  - name: install-config file
    ansible.builtin.template:
      src: install-config.conf.j2
      dest: "{{ dest_base_path }}/playbooks/roles/generate_ignition_files/ignitions/install-config.yaml"

  - name: Read ssh key file content
    slurp:
      src: /root/.ssh/id_rsa.pub
    register: file_content
    
  - name: Set pub file content to variable
    set_fact:
      pub_key: "{{ file_content.content | b64decode }}"

  - name: Replace id rsa pub key
    lineinfile:
      path: "{{ dest_base_path }}/playbooks/roles/generate_ignition_files/ignitions/install-config.yaml"
      regexp: "sshKey*"
      line: "sshKey: '{{ pub_key }}'"

  - name: Encode the password in base64
    shell: echo -n 'init:{{ lookup("file", "{{ dest_base_path }}/credentials") }}' | base64 -w0
    register: encoded_password
    when: is_environment_airgap == 'yes'

  - name: Read the content of ssl.cert
    slurp:
      src: "{{ dest_base_path }}/quay-install/quay-config/ssl.cert"
    register: ssl_cert_content
    when: is_environment_airgap == 'yes'

  - name: Set additionalTrustBundle variable
    set_fact:
      additionalTrustBundle: "{{ ssl_cert_content['content'] | b64decode }}"
    when: is_environment_airgap == 'yes'

      #  - name: install-config file
      #    ansible.builtin.template:
      #      src: install-config.conf.j2
      #      dest: "{{ base_path }}/playbooks/roles/generate_ignition_files/ignitions/install-config.yaml"

        #  - name: take the back up of install-config file
        #    copy:
        #      src: "{{ base_path }}/playbooks/roles/generate_ignition_files/ignitions/install-config.yaml"
        #      dest: "{{ base_path }}/playbooks/roles/generate_ignition_files/install-config.yaml"
      
  - name: create manifests files
    command: "{{ dest_base_path }}/playbooks/roles/download_ocp_packages/library/openshift_components/openshift-install create manifests --dir={{ dest_base_path }}/playbooks/roles/generate_ignition_files/ignitions"

  - name: create ignition files
    command: "{{ dest_base_path }}/playbooks/roles/download_ocp_packages/library/openshift_components/openshift-install create ignition-configs  --dir={{ dest_base_path }}/playbooks/roles/generate_ignition_files/ignitions"
