---     
  - name: Copy Execution environment
    block:
      - name: Copying ansible scripts to installer
        copy:
          src: "{{ dest_base_path }}/"
          dest: "{{ dest_base_path }}/"
          owner: root
          group: root
          mode: 775
          decrypt: no
