---
  - name: Fetch base path
    set_fact:
        base_path: {{ hostvars['morpheus_git_path']['morpheus_git_path'] }}/DL-LTI-Openshift
        
  - name: Copy Execution environment
    block:
      - name: Copying ansible scripts to installer
        become: true
        copy:
          src: "{{ base_path }}/"
          dest: "{{ base_path }}/"
          owner: root
          group: root
          mode: 775
          decrypt: no
