---
- name: Install required apt packages
  apt:
    name: dnsmasq
    state: present
  become: yes

- name: Check if /etc/dnsmasq.conf.bakup exists
  stat:
    path: /etc/dnsmasq.conf.bakup
  register: dnsmasq_backup_check

- name: Backup original /etc/dnsmasq.conf if not already backed up
  copy:
    src: /etc/dnsmasq.conf
    dest: /etc/dnsmasq.conf.bakup
    remote_src: yes
    mode: '0644'
  when: not dnsmasq_backup_check.stat.exists

- name: Insert DHCP scope settings in /etc/dnsmasq.conf
  blockinfile:
    path: /etc/dnsmasq.conf
    marker: "# {mark} ANSIBLE MANAGED DHCP SCOPE BLOCK"
    block: |
      interface={{ common.interface_name }}
      port=0
      domain={{ common.base_domain }}
      dhcp-option=1,{{ servers[0].Host_Netmask }}
      dhcp-option=3,{{ servers[0].Host_Gateway }}
      dhcp-option=6,{{ master_binddns }},{{ slave1_binddns }},{{ slave2_binddns }}
      dhcp-range={{ dhcp_range }}
      listen-address=::1,127.0.0.1,{{ master_binddns }}
      dhcp-authoritative
  become: yes

- name: Insert static MAC to IP mapping block
  blockinfile:
    path: /etc/dnsmasq.conf
    marker: "# {mark} ANSIBLE MANAGED STATIC MAPPINGS"
    block: |
      {% for item in ocp_bootstrap %}
      dhcp-host={{ item.mac_address }},{{ item.ip }}
      {% endfor %}
      {% for item in ocp_masters %}
      dhcp-host={{ item.mac_address }},{{ item.ip }}
      {% endfor %}
      {% for item in ocp_workers %}
      dhcp-host={{ item.mac_address }},{{ item.ip }}
      {% endfor %}
  become: yes

- name: Verify dnsmasq configuration
  command: dnsmasq --test
  register: dnsmasq_test
  changed_when: false
  failed_when: "'syntax check OK' not in dnsmasq_test.stdout"

- name: Enable and restart dnsmasq service
  service:
    name: dnsmasq
    state: restarted
    enabled: yes
  become: yes

- name: Open DHCP service in firewall
  firewalld:
    service: dhcp
    permanent: yes
    immediate: yes
    state: enabled
  become: yes
