---
- name: Copy custom ISO image to headnode1
  become: true
  copy:
    src: /tmp/ubuntu_installer_custom_iso.iso
    dest: /tmp/
    owner: root
    group: root
    mode: 0644
  vars:
    ansible_user: root

- name: Create installer vm on VME node1
  shell:
    cmd: >-
          sudo virt-install 
          --name rhocpinstaller 
          --ram 16000 
          --vcpus 4 
          --cpu host 
          --disk pool=mvm-volumes,size=250 
          --os-variant ubuntu24.04 
          --network network=Management,model=virtio,virtualport_type=openvswitch,mac={{ubuntu_installer_mac}} \
          --noautoconsole \
          --console pty,target_type=serial \
          --serial pty \
          --boot cdrom,hd \
          --autostart \
          --cdrom /tmp/ubuntu_installer_custom_iso
  delegate_to: "{{ groups['kvm_nodes'][0] }}" 

- name: ping the VM to check it's reachable
  wait_for:
    port: 22
    host: "{{ ubuntu_installer_IP }}"
    search_regex: OpenSSH
    delay: 10
