---
     - name: Fetch base path
       set_fact:
            base_path: {{ hostvars['morpheus_git_path']['morpheus_git_path'] }}/DL-LTI-Openshift
            
      - name: Copy oc to path
        become: true
        copy:
          src: "{{ base_path }}/playbooks/roles/download_ocp_packages/library/openshift_components/oc"
          dest: /usr/local/bin/
          remote_src: yes
          owner: root
          group: root
          mode: 775

      - name: Copy openshift-install to path
        become: true
        copy:
          src: "{{ base_path }}/playbooks/roles/download_ocp_packages/library/openshift_components/openshift-install"
          dest: /usr/local/bin/
          remote_src: yes
          owner: root
          group: root
          mode: 775


