---
- name: Copy ssh key to Head nodes
  hosts: localhost
  become: true
  become_user: root
  gather_facts: False
  vars_files:
    - ../input.yaml
  roles:
    - role: roles/copy_ssh/copy_ssh_headnode

