- name: Copy ssh key to ubuntu installer VM
  hosts: localhost
  become: yes
  remote_user: root
  gather_facts: False
  vars_files:
    - ../input.yaml
  roles:
    - role: roles/copy_ssh/copy_ssh_installerVM

