- name: Find Morpheus Git repo folder by remote URL
  hosts: localhost
  gather_facts: false
  vars:
    target_git_url: "https://github.com/srihithavempallihpe/hpe-solutions-openshift.git"

  tasks:
    - name: Get current user
      command: whoami
      register: whoami_output

    - name: Set base path where Git repos are stored
      set_fact:
        morpheus_git_dir: "/var/opt/morpheus/{{ whoami_output.stdout }}/repo/git"

    - name: List possible Git repo directories
      find:
        paths: "{{ morpheus_git_dir }}"
        file_type: directory
        depth: 1
      register: repo_dirs

    - name: Check each .git/config for the target Git URL
      command: grep "{{ target_git_url }}" "{{ item.path }}/.git/config"
      loop: "{{ repo_dirs.files }}"
      register: grep_results
      ignore_errors: yes

    - name: Save matching repo path as fact (if found)
      set_fact:
        morpheus_git_path: "{{ item.item.path }}"
      when: item.stdout is defined and item.stdout != ""
      loop: "{{ grep_results.results }}"
      loop_control:
        label: "{{ item.item.path }}"
      delegate_to: localhost

    - name: Add host with global fact for reuse
      add_host:
        name: morpheus_git_path_host
        morpheus_git_path: "{{ morpheus_git_path }}"
    
    - name: Set global morpheus git path
      set_fact:
        global_morpheus_git_path: "{{ item.item.path }}"
      when: item.stdout is defined and item.stdout != ""
      delegate_to: localhost
      run_once: true
      vars:
        ansible_facts:
          global_morpheus_git_path: "{{ item.item.path }}"

    - name: print path value
      debug:
        var: global_morpheus_git_path 

    - name: Display final path
      debug:
        msg: "Morpheus Git repo found at: {{ morpheus_git_path | default('Not found') }}"
