- name: Find Morpheus Git repo folder by remote URL
  hosts: localhost
  gather_facts: false
  vars:
    target_git_url: "https://github.com/srihithavempallihpe/hpe-solutions-openshift.git"

  tasks:
    - name: Check who is running this playbook
      command: whoami
      register: whoami_output

    - name: Set Morpheus Git directory dynamically
      set_fact:
        morpheus_git_dir: "/var/opt/morpheus/{{ whoami_output.stdout }}/repo/git"

    - name: Show computed Git directory
      debug:
        var: morpheus_git_dir

    - name: List all Morpheus Git repo folders
      find:
        paths: "{{ morpheus_git_dir }}"
        file_type: directory
        depth: 1
      register: repo_dirs

    - name: Check each .git/config for the target Git URL
      command: grep "{{ target_git_url }}" "{{ item.path }}/.git/config"
      loop: "{{ repo_dirs.files }}"
      register: grep_results
      ignore_errors: yes

    - name: Set matched repo path
      set_fact:
        morpheus_git_path: "{{ item.item.path }}"
      when: item.stdout is defined and item.stdout != ""
      loop: "{{ grep_results.results }}"
      loop_control:
        label: "{{ item.item.path }}"

    - name: Display matched Git repo folder
      debug:
        msg: "Morpheus repo path is {{ morpheus_git_path | default('No match found') }}"

    - name: "Add repo path to dummy host"
      add_host:
        name:   "morpheus_git_path"
        morpheus_git_path:  "{{morpheus_git_path }}"
    
    - name:
      debug:
        msg: "Morpheus git path is {{ hostvars['morpheus_git_path']['morpheus_git_path'] }}"

