- name: Find Morpheus Git repo folder by remote URL
  hosts: localhost
  gather_facts: false
  vars:
    morpheus_git_dir: "/var/opt/morpheus/morpheus-local/repo/git"
    target_git_url: "https://github.com/srihithavempallihpe/hpe-solutions-openshift.git"

  tasks:
    - name: List all Morpheus Git repo folders
      find:
        paths: "{{ morpheus_git_dir }}"
        file_type: directory
        depth: 1
      register: repo_dirs

    - name: Check each .git/config for the target Git URL
      command: grep -q "{{ target_git_url }}" "{{ item.path }}/.git/config"
      loop: "{{ repo_dirs.files }}"
      register: grep_results
      ignore_errors: yes  # Prevent Ansible from marking it failed if grep fails
      
    - name: information
      debug: grep_results
      
    - name: Set matched path as a fact
      set_fact:
        matched_git_path: "{{ item.stdout }}"
      when: item.stdout != ""
      loop: "{{ grep_results.results }}"
      loop_control:
        label: "{{ item.item.path }}"

    - name: Display matched Git repo folder
      debug:
        msg: "Morpheus repo path is {{ matched_git_path }}"
