---
- hosts: infra_vm
  become: yes
  gather_facts: no
  vars_files: ../input.yaml
  remote_user: root
  roles:
    - { role: roles/ocp_network/binddns }

- name: Deploy dnsmasq service
  hosts: infra_vm
  become: true
  gather_facts: False
  remote_user: root
  vars_files:
    - ../input.yaml
  roles:
    - { role: roles/ocp_network/haproxy }

- hosts: infra_vm
  become: true
  remote_user: root
  vars_files: ../input.yaml
  gather_facts: True
  roles:
    - { role: roles/ocp_network/dnsmasq }