- name: Create master1 VM on KVM node1
  shell:
    cmd: >-
        virt-install
        -n demo-vm
        --description "vm creation for demo"
        --memory={{ morpheus['customOptions']['vm_mem'] }}
        --vcpus={{ morpheus['customOptions']['vm_cpu'] }}  
        --location /root/ubuntu-22.04.5-live-server-amd64.iso 
        --os-variant=ubuntu22.04
        --disk path=/mnt/ocp_vms/demo-vm.qcow2,bus=virtio,size={{ morpheus['customOptions']['vm_size'] }}
        --autostart 
        --graphics none
        --extra-args "console=ttyS0,115200n8 serial"
        --console pty,target_type=virtio
        --network bridge:{{ morpheus['customOptions']['common']['interface_name'] }},mac.address={{  morpheus['customOptions']['ocp_masters'][0]['mac_address'] }}
        --wait 10
  delegate_to: "{{ groups['all'][0] }}" 
