---
  - name: Find full ISO file path via shell (no sudo)
    become: true
    shell: |
      find /var/opt/morpheus/morpheus-ui/vms/morpheus-images/morpheus-virtual-images/ -type f -name "{{ config.OS_image_name }}" 2>/dev/null | head -n 1
    register: iso_path
    delegate_to: localhost
    run_once: true

  - name: Print all matching ISO files with full paths
    debug:
      var: iso_path.stdout
    
  - name: Set ISO full path as fact
    set_fact:
      iso_full_path: "{{ iso_path.stdout }}"
    when: iso_path.stdout != ""
    delegate_to: localhost

  - name: Make ISO world-readable copy
    become: true
    shell: cp {{iso_full_path}} /tmp/ && chmod 644 /tmp/rhel9.iso
    delegate_to: localhost
    run_once: true
  
  - name: Copy ISO image to headnode1
    become: true
    copy:
      src: /tmp/rhel9.iso
      dest: /tmp/
      owner: root
      group: root
      mode: 0644

  - name: copy ks.cfg file to head node
    become: true
    template:
      src: ks.conf.j2
      dest: /tmp/ks.cfg
      owner: root
      group: root
      mode: 777
    delegate_to: localhost
    run_once: true

  - name: create installer VM on KVM node1
    shell:
      cmd: >-
          virt-install
          --name rhel9_installer
          --memory=16000
          --vcpus=4
          --os-type linux
          --location /tmp/{{ config.OS_image_name }}
          --disk path=/mnt/ocp_vms/installer.qcow2,device=disk,size=250,bus=virtio
          --network bridge={{ common.interface_name }}
          --os-variant=rhel9.0
          --autostart
          --console pty,target_type=virtio
          --initrd-inject /tmp/ks.cfg
          --extra-args "inst.ks=file:/ks.cfg console=tty0 console=ttyS0,115200n8"
          --wait 12

  - name: ping the VM to check it's reachable
    wait_for:
      port: 22
      host: "{{ rhel9_installer_IP }}"
      search_regex: OpenSSH
      delay: 10

